### ISSUE TITLE
Automatic serialisation / deserialisation

### ISSUE THREAD

**Issue by neographikal** [andrew-bn/RedisBoost#1]
I'm using redisboost for the first time, I'm wondering: why isn't stuff automatically deserialised to the type it was?

Great job btw :)

**Comment by andrew-bn** [comment]
Hi, 
To do so, the type of serialized object should be known beforehand. Currently Serializer interface does not imply saving this information along with serialized object.

But let's imagine that this metadata information is saved and even if we know the type  of serialized object, there may be situations then it is imposible to create an instance of this type because the assembly is not loaded to the appdomain.
Such situations are possible if, for example, some client just reads data from Redis as bytes array and knows nothing about the type of the object that was serialized.

Let's say that we somehow detected Type of object and successfuly deserialized data to the instance of that type. In this case the only thing we can return to client is instance of Object type. Here client is forced to cast this object to some known type. 
If cast is done by AS operator then NULL references are possible.
Also the cast to specific type can be done far from the place of getting data from Redis.

``` CSharp
	
	cli.SetAsync("Key", new MyObject()).Wait(); // store object of type MyObject
	byte[] result = cli.GetAsync("Key").Result; //implicit conversion to byte[]
	var result = cli.GetAsync("Key").Result.Deserialize(); //implicit decerialization to autodetected type - MyObject. The result is Object.
	
	// ... some code here
	// ...
	var myObjectResult = (MyObject)result; // possible InvalidCastException
	myObjectResult = result as MyObject; // possible Null reference

```

**Comment by neographikal** [comment]
Cool thanks for the extensive explanation. I thought of the problems of not having the correct assembly present (which would something I could live with) but the debugging might be a problem idd. Thanks again :)
