### ISSUE TITLE
ReadMessageAsync and connection failure

### ISSUE THREAD

**Issue by kilroytrout** [andrew-bn/RedisBoost#4]
Andrew 
I'm creating a wrapper for pub/sub using RedisBoost, and it has logic to handle connection loss/reconnect. Generally your RedisClient API's raise RedisExceptions in this scenerio, but ReadMessageAsync() apparently eats any underlying exception and returns a ChannelMessageType.Unknown as the only indication that something went wrong. Is this by design? Shouldn't it raise a RedisException in this case?

**Comment by andrew-bn** [comment]
Hi,
yes you are right. This logic was introduced in version 1.5.5 with such description

*If command is called without filter, then all errors and unknown packets are returned to client without exceptions thrown. If ReadMessageAsync is called with filter, then exception is thrown if error occured or unknown packet was received. So ReadMessageAsync without filter is guaranteed to be exceptionless.*

Now, I think that such behavior should be revised because it does not give a proper understanding of what is going on with channel.

So, what if:
- ReadMessageAsync() raises RedisException if some socket issue happened, returns Unknown message if the format of received message is not valid (http://redis.io/topics/pubsub)
- ReadMessageAsync(filter) raises RedisException if some socket issue happened (inner exception will be preserved), raises RedisException if Unknown packed was received

**Comment by kilroytrout** [comment]
Andrew yes I think that change would be good - thanks.

**Comment by andrew-bn** [comment]
Hi,
New version was released: RedisBoost 1.6.3.
Please try it.
